#==========================================================================
# Description: Build Armbian
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#==========================================================================

name: testonly

on:
  repository_dispatch:
  workflow_dispatch:
   
jobs:
 build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

   
    steps:
      
      # 上传打包文件到远程服务器
      - name: Upload file
        uses: tomasbkk/action-ftp-upload@v1.0
        with:
            user: 3398862633
            password: 3398862633
            host: 43.128.250.47
            src:  root/*
            dest: archive/


     
